#!/usr/bin/env python3
"""Structural diagnostics for the single reader-facing humanvoice proposal.

These checks protect the document boundary, citation integrity, and a few
reader-facing hazards. They are deliberately not a readability or persuasion
test. A complete rendered read and a human decision remain necessary.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DOCUMENT = ROOT / "docs" / "survey" / "humanvoice_survey.tex"
DEFAULT_BIBLIOGRAPHY = ROOT / "docs" / "survey" / "humanvoice_survey.bib"


def bibliography_keys(text: str) -> set[str]:
    return set(re.findall(r"^\s*@\w+\s*\{\s*([^,\s]+)", text, flags=re.MULTILINE))


def citation_keys(text: str) -> set[str]:
    keys: set[str] = set()
    for match in re.finditer(
        r"\\cite[a-zA-Z*]*\s*(?:\[[^]]*\]\s*)?\{([^}]*)\}", text
    ):
        keys.update(part.strip() for part in match.group(1).split(",") if part.strip())
    return keys


def expand_inputs(text: str, base_dir: Path | None = None) -> str:
    """Inline local TeX inputs so diagnostics cover the complete manuscript."""
    base = base_dir or DEFAULT_DOCUMENT.parent

    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        candidate = base / name
        if candidate.suffix == "":
            candidate = candidate.with_suffix(".tex")
        if not candidate.is_file():
            return match.group(0)
        return candidate.read_text(encoding="utf-8")

    previous = None
    expanded = text
    while previous != expanded:
        previous = expanded
        expanded = re.sub(r"\\input\{([^}]+)\}", replace, expanded)
    return expanded


def main_route(text: str) -> str:
    """Return the reader-facing body, excluding technical appendices."""
    return text.split("\\appendix", 1)[0]


def _word_count(text: str) -> int:
    without_commands = re.sub(
        r"\\[a-zA-Z]+\*?(?:\[[^]]*\])?(?:\{[^{}]*\})?", " ", text
    )
    without_math = re.sub(r"\$[^$]*\$", " ", without_commands)
    return len(re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", without_math))


def document_checks(document: str, bibliography: str) -> dict[str, bool]:
    expanded = expand_inputs(document)
    route = main_route(expanded)
    route_lower = route.lower()
    expanded_lower = expanded.lower()
    route_flat = re.sub(r"\s+", " ", route).strip().lower()
    headings = set(
        re.findall(r"^\\(?:chapter|section)\{([^}]*)\}", route, flags=re.MULTILINE)
    )
    required_headings = {
        "Why good documents still fail",
        "Inside a Humanvoice review",
        "Evidence, promise, and limits",
        "Where Humanvoice fits",
        "How the product works",
        "The first build",
        "The test and its economics",
        "Twelve weeks to a decision",
    }
    forbidden_backstage = (
        "a short history of this document",
        "generated by tools/survey_audit.py",
        "status: release blocked",
        "protocol id",
        "search events:",
        "screening queue",
        "artifact manifest",
        "two-document setup",
        "separate proposal and survey",
        "supporting survey",
    )
    forbidden_split_language = (
        "two-document setup",
        "separate proposal and survey",
        "supporting survey",
        "choose between a proposal and a survey",
    )
    # The bibliography serves the complete monograph, including its technical
    # appendices. Validate citation coverage at that same boundary while the
    # other reader-facing diagnostics continue to use ``route``.
    all_citations = citation_keys(expanded)
    available = bibliography_keys(bibliography)
    route_word_count = _word_count(route)
    repeated_template = len(
        re.findall(r"Consequences for the design", route, flags=re.IGNORECASE)
    )
    chapter_titles = re.findall(r"^\\chapter\{([^}]*)\}", route, flags=re.MULTILINE)
    legacy_commands = re.compile(
        r"\\texttt\{hv (?:snapshot|revise|reader|report|gate|diff)\}",
        flags=re.IGNORECASE,
    )
    private_requirement_ids = re.compile(r"\b(?:WP|R)(?:[1-9]|1[0-9])\b")
    markdown_mvp_claims = (
        "two source formats in the mvp: latex and markdown",
        "mvp is complete when one latex or markdown document",
        "evaluation corpus for latex and markdown",
    )

    return {
        "single_title_present": "making expert technical documents easier to understand"
        in expanded.lower(),
        "reader_facing_chapter_spine_present": required_headings.issubset(headings),
        "opening_has_decision_request": "decision requested" in expanded.lower()
        and "twelve-week mvp" in expanded.lower(),
        "opening_has_concrete_reader_problem": "expert reader" in route_lower
        and "feedback" in route_lower
        and "rereading" in route_lower,
        "product_has_end_to_end_case": all(
            phrase in route_lower
            for phrase in (
                "source snapshot",
                "located findings",
                "protected comparison",
                "reader decision",
            )
        ),
        "product_has_protected_objects": "protectedspan" in route_lower
        and "equations" in route_lower
        and "citation" in route_lower,
        "pre_human_authoring_contract_present": all(
            phrase in route_lower
            for phrase in (
                "authoring brief",
                "argument blueprint",
                "concept-dependency graph",
                "pre-human preflight",
                "fail-closed",
                "human-attention budget",
            )
        ),
        "pre_human_release_path_present": all(
            phrase in route_lower
            for phrase in (
                r"\texttt{hv init}",
                r"\texttt{hv plan}",
                r"\texttt{hv draft}",
                r"\texttt{hv preflight}",
                r"\texttt{hv repair}",
                r"\texttt{hv release}",
            )
        ),
        "evidence_is_synthesized": "evidence-to-design synthesis" in route_lower
        and "evidence, promise, and limits" in route_lower,
        "evaluation_has_estimand": "eq:estimand" in route
        and "incumbent bundle" in route_lower,
        "economics_has_sensitivity": "eq:value" in route
        and "symbolic sensitivity" in route_lower,
        "implementation_has_resource_envelope": "person-weeks" in route_lower
        and "proceed, revise, or stop" in route_lower,
        # The canonical route must retain the substantive source chapters and
        # the expansion spine. This is a floor against accidental recompression,
        # not a claim that word count proves quality.
        "expanded_substantive_route_present": all(
            phrase in route
            for phrase in (
                "The cases that made the problem visible",
                "Research on AI-assisted writing",
                "Open-source tools",
                "How we reviewed the evidence",
                "Who would use it, and why",
            )
        ),
        "expanded_exemplar_spine_present": all(
            phrase.lower() in route_flat
            for phrase in (
                "One document, from draft to decision",
                "The research behind Humanvoice",
                "Components worth testing",
                "Architecture for reversible review",
                "A comparative test",
                "From prototype to service",
                "Foundations of writing as planned work",
                "The alternatives an executive will try first",
                "Buy the parts, build the connection",
                "A fixture decides, not a feature list",
                "The internal record and the external literature now give the case a wider test",
            )
        ),
        "hpo_case_and_diagnostic_ladder_present": all(
            phrase in route_flat
            for phrase in (
                "a live lesson in density",
                "paragraph packing",
                "conceptual pacing",
                "dependency order",
                "not acceptance thresholds",
            )
        ),
        "hpo_operational_records_present": all(
            phrase in expanded_lower
            for phrase in (
                "eq:pacing-profile",
                "tab:pacing-order-assertion-records",
                "stopping point",
                "assertion audit",
            )
        ),
        "hpo_fixture_boundary_present": all(
            phrase in expanded_lower
            for phrase in (
                "app:hpo-density-record",
                "25 adjudicated",
                "80 passages",
                "one engagement",
            )
        ),
        "expanded_route_word_floor": route_word_count >= 50000,
        "no_backstage_scaffolding_in_route": not any(
            term in route_lower for term in forbidden_backstage
        ),
        # Compatibility names retained for the focused regression tests. They
        # remain diagnostics, not acceptance claims.
        "no_history_or_audit_scaffolding_in_route": not any(
            term in route_lower for term in forbidden_backstage
        ),
        "no_split_document_language": not any(
            term in route_lower for term in forbidden_split_language
        ),
        "no_repeated_survey_template": repeated_template <= 1,
        "no_questionnaire_style_chapter_titles": not any(
            title.lower().startswith("what ") for title in chapter_titles
        ),
        "no_private_requirement_ids_in_route": not private_requirement_ids.search(route),
        "one_command_vocabulary": not legacy_commands.search(route),
        "latex_first_scope_is_consistent": not any(
            phrase in route_lower for phrase in markdown_mvp_claims
        ),
        "appendix_present": "\\appendix" in expanded and "sec:app" not in route_lower,
        "bibliography_present": "\\bibliography{humanvoice_survey}" in expanded,
        "all_citations_have_bibliography_entries": all_citations.issubset(available),
        "no_uncited_bibliography_entries": available.issubset(all_citations),
        "no_unresolved_authoring_markers": not re.search(
            r"\b(?:TODO|TBD|FIXME|XXX)\b", route
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("document", nargs="?", default=str(DEFAULT_DOCUMENT))
    parser.add_argument("--bibliography", default=str(DEFAULT_BIBLIOGRAPHY))
    args = parser.parse_args()

    document_path = Path(args.document).resolve()
    bibliography_path = Path(args.bibliography).resolve()
    document = document_path.read_text(encoding="utf-8")
    bibliography = bibliography_path.read_text(encoding="utf-8")
    checks = document_checks(document, bibliography)
    for name, passed in checks.items():
        print(f"{'PASS' if passed else 'FAIL'} {name}")

    expanded = expand_inputs(document)
    route = main_route(expanded)
    print(f"INFO main_route_words={_word_count(route)}")
    print(
        "DIAGNOSTIC ONLY: these checks do not establish readability, scholarship "
        "completeness, persuasion, or human acceptance."
    )
    return 0 if all(checks.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
