import unittest
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_humanvoice_document import document_checks


ROOT = Path(__file__).resolve().parents[1]


class ProductProposalChecksTests(unittest.TestCase):
    def setUp(self):
        self.proposal = (ROOT / "docs/survey/humanvoice_survey.tex").read_text(encoding="utf-8")
        self.bibliography = (ROOT / "docs/survey/humanvoice_survey.bib").read_text(encoding="utf-8")

    def test_unified_document_passes_structural_diagnostics(self):
        checks = document_checks(self.proposal, self.bibliography)
        self.assertTrue(all(checks.values()), [name for name, passed in checks.items() if not passed])

    def test_generated_audit_opening_is_rejected(self):
        contaminated = self.proposal.replace(
            "\\input{proposal/00_orientation}",
            "Status: RELEASE BLOCKED. Generated by `tools/survey_audit.py`. Search events: 42.\n\n\\input{proposal/00_orientation}",
            1,
        )
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["no_history_or_audit_scaffolding_in_route"])

    def test_unknown_citation_is_rejected(self):
        contaminated = self.proposal.replace("\\appendix", "\\citep{not_a_real_source}\n\\appendix", 1)
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["all_citations_have_bibliography_entries"])

    def test_split_language_is_rejected(self):
        contaminated = self.proposal.replace(
            "\\input{proposal/00_orientation}",
            "\\input{proposal/00_orientation}\n\\textit{supporting survey}",
            1,
        )
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["no_split_document_language"])

    def test_worked_product_case_is_required(self):
        contaminated = "\\chapter{Inside a Humanvoice review}"
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["product_has_end_to_end_case"])

    def test_private_register_and_legacy_commands_are_rejected(self):
        contaminated = self.proposal.replace(
            "\\appendix",
            "\\section{What is being authorized}\\texttt{hv report} R12\\appendix",
            1,
        )
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["no_private_requirement_ids_in_route"])
        self.assertFalse(checks["one_command_vocabulary"])

    def test_evaluation_and_economics_are_required(self):
        contaminated = "\\chapter{The test and the economics}"
        checks = document_checks(contaminated, self.bibliography)
        self.assertFalse(checks["evaluation_has_estimand"])

    def test_expanded_route_retains_substantive_source_material(self):
        checks = document_checks(self.proposal, self.bibliography)
        self.assertTrue(checks["expanded_substantive_route_present"])
        self.assertTrue(checks["expanded_exemplar_spine_present"])
        self.assertTrue(checks["expanded_route_word_floor"])


if __name__ == "__main__":
    unittest.main()
